<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260730115741 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE question (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number INT DEFAULT NULL, question_text TEXT NOT NULL, answer_text TEXT NOT NULL, is_answered BOOLEAN NOT NULL, session_id INT NOT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B6F7494E613FECDF ON question (session_id)');
        $this->addSql('CREATE INDEX IDX_B6F7494E59027487 ON question (theme_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_session_number ON question (session_id, number)');
        $this->addSql('CREATE TABLE session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_shuffled BOOLEAN NOT NULL, reveal_duration INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE theme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(7) NOT NULL, session_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9775E708613FECDF ON theme (session_id)');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT FK_B6F7494E59027487 FOREIGN KEY (theme_id) REFERENCES theme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE theme ADD CONSTRAINT FK_9775E708613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494E613FECDF');
        $this->addSql('ALTER TABLE question DROP CONSTRAINT FK_B6F7494E59027487');
        $this->addSql('ALTER TABLE theme DROP CONSTRAINT FK_9775E708613FECDF');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE session');
        $this->addSql('DROP TABLE theme');
    }
}
