<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260730160148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE player (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, score INT NOT NULL, session_id INT NOT NULL, theme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98197A65613FECDF ON player (session_id)');
        $this->addSql('CREATE INDEX IDX_98197A6559027487 ON player (theme_id)');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65613FECDF FOREIGN KEY (session_id) REFERENCES session (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A6559027487 FOREIGN KEY (theme_id) REFERENCES theme (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE session ADD current_player_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE session ADD CONSTRAINT FK_D044D5D442C04473 FOREIGN KEY (current_player_id) REFERENCES player (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_D044D5D442C04473 ON session (current_player_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65613FECDF');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A6559027487');
        $this->addSql('DROP TABLE player');
        $this->addSql('ALTER TABLE session DROP CONSTRAINT FK_D044D5D442C04473');
        $this->addSql('DROP INDEX IDX_D044D5D442C04473');
        $this->addSql('ALTER TABLE session DROP current_player_id');
    }
}
